---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: console-api
  template:
    metadata:
      labels:
        app: console-api
    spec:
      containers:
        - name: console-api
          image: ghcr.io/kriipke/console-api:latest
          imagePullPolicy: always
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthchecker
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthchecker
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
